
module.exports = {
  'prefer-promise-reject-errors': [0],
  'no-negated-condition': [0],
  'operator-linebreak': [1, 'before'],
  'unicorn/escape-case': [0],
  'prefer-destructuring': [0],
  'capitalized-comments': [0],
  'space-unary-ops': [0],
  'import/no-unresolved': [0, 'nerver'],
  'import/no-unassigned-import': [0, 'nerver'],
  'import/order': [0, 'nerver'],
  'new-cap': [1, {
    newIsCap: true,
    capIsNew: false,
  }],
  'no-implicit-coercion': [0],
  'array-element-newline': [0],
  'array-callback-return': [0],
  'no-return-assign': [1, 'except-parens'],
  'curly': [1, 'multi-line'],
  'semi': [0, 'never'],
  'no-console': [0],
  'no-global-assign': [0],
  'eqeqeq': [1],
  'no-eval': [1],
  'no-undef': [1],
  'no-debugger': [1],
  'prefer-const': [1],
  'default-case': [1],
  'no-fallthrough': [1],
  'no-unused-vars': [1],
  'no-unreachable': [1],
  'no-new-wrappers': [1],
  'no-multi-spaces': [1],
  'no-sparse-arrays': [1],
  'no-constant-condition': [1],
  'no-unused-expressions': [1, {
    allowShortCircuit: true,
  }],
  'quotes': [1, 'single'],
  'eol-last': [1, 'always'],
  'linebreak-style': [1, 'unix'],
  'indent': [1, 2, { 'SwitchCase': 1 }],
  'no-cond-assign': [1, 'except-parens'],
  'comma-dangle': [1, 'always-multiline'],
  'space-infix-ops': [1, { 'int32Hint': true }],
  'object-curly-spacing': [1, 'always'],
  'keyword-spacing': [1, { before: true, after: true }],
  'lines-around-comment': [1, {
    'beforeBlockComment': true,
  }],
}
